name: Build and run contract unit tests

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
            node-version: 16.x
      - name: Clean cache and node modules
        run: |
          rm -rf node_modules 
          rm -f package-lock.json
          rm -f yarn.lock
      - name: Install dependencies
        run: npm install
      - name: Compile and Unit test contracts
        run: npm run test
      - name: Local deployment
        env:
          VALIDATORS: 0x70997970C51812dc3A010C7d01b50e0d17dc79C8,0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
        run: |
          cp .env.example .env
          npx hardhat node &
          yarn deploy
          npx hardhat --network local run scripts/deploy-keccak256/register.js
          npx hardhat --network local run scripts/deploy-keccak256/addTokens.js
          npx hardhat --network local run scripts/deploy-keccak256/deposit.js
